---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

version: '3.7'

services:
  adguard:
    image: 'adguard/adguardhome'
    restart: 'unless-stopped'
    networks:
    - 'traefik'
    ports:
    - '$HOST:53:53/udp'
    - '$HOST:53:53/tcp'
    volumes:
    - type: 'volume'
      source: 'config'
      target: '/opt/adguardhome/conf'
    - type: 'volume'
      source: 'work'
      target: '/opt/adguardhome/work'
    labels:
    - 'traefik.enable=true'
    - 'traefik.docker.network=traefik'
    - 'traefik.http.routers.adguard.rule=Host(`$HOSTNAME.$DOMAIN`)'
    - 'traefik.http.routers.adguard.entrypoints=websecure'
    - 'traefik.http.routers.adguard.middlewares=$MIDDLEWARE'
    - 'traefik.http.routers.adguard.service=adguard'
    - 'traefik.http.services.adguard.loadbalancer.passhostheader=true'
    - 'traefik.http.services.adguard.loadbalancer.server.port=3000'

networks:
  traefik:
    external: true

volumes:
  config: {}
  work: {}
